export default {
    u1F600: {
        en: 'grinning',
        zh: '大笑',
        tag: '😀',
        bp: '0px 0px',
    },
    u1F601: {
        en: 'grin',
        zh: '露齿而笑',
        tag: '😁',
        bp: '-25px 0px',
    },
    u1F602: {
        en: 'joy',
        zh: '破涕为笑',
        tag: '😂',
        bp: '-50px 0px',
    },
    u1F603: {
        en: 'smile',
        zh: '微笑',
        tag: '😃',
        bp: '-75px 0px',
    },
    u1F605: {
        en: 'sweat_smile',
        zh: '赔笑',
        tag: '😅',
        bp: '-100px 0px',
    },
    u1F606: {
        en: 'satisfied',
        zh: '满意',
        tag: '😆',
        bp: '-125px 0px',
    },
    u1F607: {
        en: 'innocent',
        zh: '纯洁',
        tag: '😇',
        bp: '-150px 0px',
    },
    u1F608: {
        en: 'smiling_imp',
        zh: '坏笑',
        tag: '😈',
        bp: '-175px 0px',
    },
    u1F609: {
        en: 'wink',
        zh: '眨眼',
        tag: '😉',
        bp: '-200px 0px',
    },
    u1F611: {
        en: 'expressionless',
        zh: '面无表情',
        tag: '😑',
        bp: '-225px 0px',
    },
    u1F612: {
        en: 'unamused',
        zh: '鄙視',
        tag: '😒',
        bp: '-250px 0px',
    },
    u1F613: {
        en: 'sweat',
        zh: '汗',
        tag: '😓',
        bp: '-275px 0px',
    },
    u1F614: {
        en: 'pensive',
        zh: '哀思',
        tag: '😔',
        bp: '-300px 0px',
    },
    u1F615: {
        en: 'confused',
        zh: '迷茫',
        tag: '😕',
        bp: '-325px 0px',
    },
    u1F616: {
        en: 'confounded',
        zh: '困惑的',
        tag: '😖',
        bp: '-350px 0px',
    },
    u1F618: {
        en: 'kissing_heart',
        zh: '亲一个',
        tag: '😘',
        bp: '-375px 0px',
    },
    u1F621: {
        en: 'rage',
        zh: '愤怒',
        tag: '😡',
        bp: '-400px 0px',
    },
    u1F62D: {
        en: 'sob',
        zh: '哭泣',
        tag: '😭',
        bp: '-425px 0px',
    },
    u1F623: {
        en: 'persevere',
        zh: '使劲',
        tag: '😣',
        bp: '-450px 0px',
    },
    u1F624: {
        en: 'triumph',
        zh: '生气',
        tag: '😤',
        bp: '-475px 0px',
    },
    u1F628: {
        en: 'fearful',
        zh: '可怕',
        tag: '😨',
        bp: '-500px 0px',
    },
    u1F629: {
        en: 'weary',
        zh: '厌倦',
        tag: '😩',
        bp: '-525px 0px',
    },
    u1F630: {
        en: 'cold_sweat',
        zh: '冷汗',
        tag: '😰',
        bp: '-550px 0px',
    },
    u1F631: {
        en: 'scream',
        zh: '惊叫',
        tag: '😱',
        bp: '-575px 0px',
    },
    u1F632: {
        en: 'astonished',
        zh: '惊讶',
        tag: '😲',
        bp: '-600px 0px',
    },
    u1F633: {
        en: 'flushed',
        zh: '呆住',
        tag: '😳',
        bp: '-625px 0px',
    },
    u1F634: {
        en: 'sleeping',
        zh: '睡眠',
        tag: '😴',
        bp: '-650px 0px',
    },
    u1F635: {
        en: 'dizzy_face',
        zh: '断电了',
        tag: '😵',
        bp: '-675px 0px',
    },
    u1F636: {
        en: 'no_mouth',
        zh: '无口',
        tag: '😶',
        bp: '-700px 0px',
    },
    u1F637: {
        en: 'mask',
        zh: '病了',
        tag: '😷',
        bp: '-725px 0px',
    },
    u1F3A4: {
        en: 'microphone',
        zh: 'KTV',
        tag: '🎤',
        bp: '-750px 0px',
    },
    u1F3B2: {
        en: 'game_die',
        zh: '色子',
        tag: '🎲',
        bp: '-775px 0px',
    },
    u1F3B5: {
        en: 'musical_note',
        zh: '音乐',
        tag: '🎵',
        bp: '-800px 0px',
    },
    u1F3C0: {
        en: 'basketball',
        zh: '篮球',
        tag: '🏀',
        bp: '-825px 0px',
    },
    u1F3C2: {
        en: 'snowboarder',
        zh: '单板滑雪',
        tag: '🏂',
        bp: '-850px 0px',
    },
    u1F3E1: {
        en: 'house_with_garden',
        zh: '房子',
        tag: '🏡',
        bp: '-876px 0px',
    },
    u1F004: {
        en: 'mahjong',
        zh: '麻将',
        tag: '🀄',
        bp: '-900px 0px',
    },
    u1F4A1: {
        en: 'bulb',
        zh: '灯泡',
        tag: '💡',
        bp: '-925px 0px',
    },
    u1F4A2: {
        en: 'anger',
        zh: '爆筋',
        tag: '💢',
        bp: '-950px 0px',
    },
    u1F4A3: {
        en: 'bomb',
        zh: '炸弹',
        tag: '💣',
        bp: '-975px 0px',
    },
    u1F4A4: {
        en: 'zzz',
        zh: 'ZZZ',
        tag: '💤',
        bp: '-1000px 0px',
    },
    u1F4A9: {
        en: 'shit',
        zh: '便便',
        tag: '💩',
        bp: '-1025px 0px',
    },
    u1F4AA: {
        en: 'muscle',
        zh: '肌肉',
        tag: '💪',
        bp: '-1050px 0px',
    },
    u1F4B0: {
        en: 'moneybag',
        zh: '钱袋',
        tag: '💰',
        bp: '-1075px 0px',
    },
    u1F4DA: {
        en: 'books',
        zh: '书籍',
        tag: '📚',
        bp: '-1100px 0px',
    },
    u1F4DE: {
        en: 'telephone_receiver',
        zh: '电话',
        tag: '📞',
        bp: '-1125px 0px',
    },
    u1F4E2: {
        en: 'loudspeaker',
        zh: '扩音器',
        tag: '📢',
        bp: '-1150px 0px',
    },
    u1F6AB: {
        en: 'stop',
        zh: '停止',
        tag: '🚫',
        bp: '-1175px 0px',
    },
    u1F6BF: {
        en: 'shower',
        zh: '淋浴',
        tag: '🚿',
        bp: '-1200px 0px',
    },
    u1F30F: {
        en: 'earth_asia',
        zh: '地球',
        tag: '🌏',
        bp: '-1225px 0px',
    },
    u1F33B: {
        en: 'sunflower',
        zh: '向日葵',
        tag: '🌻',
        bp: '-1250px 0px',
    },
    u1F35A: {
        en: 'rice',
        zh: '吃饭',
        tag: '🍚',
        bp: '-1275px 0px',
    },
    u1F36B: {
        en: 'chocolate_bar',
        zh: '巧克力',
        tag: '🍫',
        bp: '-1300px 0px',
    },
    u1F37B: {
        en: 'beers',
        zh: '啤酒',
        tag: '🍻',
        bp: '-1325px 0px',
    },
    u270A: {
        en: 'fist',
        zh: '拳头',
        tag: '✊',
        bp: '-1350px 0px',
    },
    u1F44C: {
        en: 'ok_hand',
        zh: '没问题',
        tag: '👌',
        bp: '-1375px 0px',
    },
    u1F44D: {
        en: '+1',
        zh: '点赞',
        tag: '👍',
        bp: '-1400px 0px',
    },
    u1F44E: {
        en: '-1',
        zh: '踩',
        tag: '👎',
        bp: '-1425px 0px',
    },
    u1F44F: {
        en: 'clap',
        zh: '拍',
        tag: '👏',
        bp: '-1450px 0px',
    },
    u1F46A: {
        en: 'family',
        zh: '家庭',
        tag: '👪',
        bp: '-1475px 0px',
    },
    u1F46B: {
        en: 'couple',
        zh: '情侣',
        tag: '👫',
        bp: '-1500px 0px',
    },
    u1F62C: {
        en: 'grimacing',
        zh: '鬼脸',
        tag: '😬',
        bp: '-1525px 0px',
    },
    u1F47B: {
        en: 'ghost',
        zh: '鬼',
        tag: '👻',
        bp: '-2050px 0px',
    },
    u1F47C: {
        en: 'angel',
        zh: '天使',
        tag: '👼',
        bp: '-1550px 0px',
    },
    u1F47D: {
        en: 'alien',
        zh: '外星人',
        tag: '👽',
        bp: '-1575px 0px',
    },
    u1F47F: {
        en: 'imp',
        zh: '恶魔',
        tag: '👿',
        bp: '-1600px 0px',
    },
    u1F48A: {
        en: 'pill',
        zh: '药丸',
        tag: '💊',
        bp: '-1625px 0px',
    },
    u1F48B: {
        en: 'kiss',
        zh: '吻',
        tag: '💋',
        bp: '-1650px 0px',
    },
    u1F48D: {
        en: 'ring',
        zh: '戒指',
        tag: '💍',
        bp: '-1675px 0px',
    },
    u1F52B: {
        en: 'gun',
        zh: '枪',
        tag: '🔫',
        bp: '-1700px 0px',
    },
    u1F60A: {
        en: 'blush',
        zh: '脸红',
        tag: '😊',
        bp: '-1725px 0px',
    },
    u1F60B: {
        en: 'yum',
        zh: '馋',
        tag: '😋',
        bp: '-1750px 0px',
    },
    u1F60C: {
        en: 'relieved',
        zh: '安心',
        tag: '😌',
        bp: '-1775px 0px',
    },
    u1F60D: {
        en: 'heart_eyes',
        zh: '色色',
        tag: '😍',
        bp: '-1800px 0px',
    },
    u1F60E: {
        en: 'sunglasses',
        zh: '墨镜',
        tag: '😎',
        bp: '-1825px 0px',
    },
    u1F60F: {
        en: 'smirk',
        zh: '傻笑',
        tag: '😏',
        bp: '-1850px 0px',
    },
    u1F61A: {
        en: 'kissing_closed_eyes',
        zh: '接吻',
        tag: '😚',
        bp: '-1875px 0px',
    },
    u1F61C: {
        en: 'stuck_out_tongue_winking_eye',
        zh: '搞怪',
        tag: '😜',
        bp: '-1900px 0px',
    },
    u1F61D: {
        en: 'stuck_out_tongue_closed_eyes',
        zh: '恶作剧',
        tag: '😝',
        bp: '-1925px 0px',
    },
    u1F61E: {
        en: 'disappointed',
        zh: '失望的',
        tag: '😞',
        bp: '-1950px 0px',
    },
    u1F61F: {
        en: 'anguished',
        zh: '苦涩',
        tag: '😟',
        bp: '-1975px 0px',
    },
    u1F62A: {
        en: 'sleepy',
        zh: '困',
        tag: '😪',
        bp: '-2000px 0px',
    },
    u1F62B: {
        en: 'tired_face',
        zh: '抓狂',
        tag: '😫',
        bp: '-2025px 0px',
    },
    u1F622: {
        en: 'cry',
        zh: '哭',
        tag: '😢',
        bp: '-2075px 0px',
    },
    u1F62F: {
        en: 'hushed',
        zh: '寂静',
        tag: '😯',
        bp: '-2100px 0px',
    },
    u1F64A: {
        en: 'speak_no_evil',
        zh: '不说话',
        tag: '🙊',
        bp: '-2125px 0px',
    },
    u1F64F: {
        en: 'pray',
        zh: '祈祷',
        tag: '🙏',
        bp: '-2150px 0px',
    },
    u1F319: {
        en: 'moon',
        zh: '月亮',
        tag: '🌙',
        bp: '-2175px 0px',
    },
    u1F332: {
        en: 'evergreen_tree',
        zh: '树',
        tag: '🌲',
        bp: '-2200px 0px',
    },
    u1F339: {
        en: 'rose',
        zh: '玫瑰',
        tag: '🌹',
        bp: '-2225px 0px',
    },
    u1F349: {
        en: 'watermelon',
        zh: '西瓜',
        tag: '🍉',
        bp: '-2250px 0px',
    },
    u1F356: {
        en: 'meat_on_bone',
        zh: '肉',
        tag: '🍖',
        bp: '-2275px 0px',
    },
    u1F366: {
        en: 'icecream',
        zh: '冰淇淋',
        tag: '🍦',
        bp: '-2300px 0px',
    },
    u1F377: {
        en: 'wine_glass',
        zh: '酒',
        tag: '🍷',
        bp: '-2325px 0px',
    },
    u1F381: {
        en: 'gift',
        zh: '礼物',
        tag: '🎁',
        bp: '-2350px 0px',
    },
    u1F382: {
        en: 'birthday',
        zh: '生日',
        tag: '🎂',
        bp: '-2375px 0px',
    },
    u1F384: {
        en: 'christmas_tree',
        zh: '圣诞',
        tag: '🎄',
        bp: '-2400px 0px',
    },
    u1F389: {
        en: 'tada',
        zh: '礼花',
        tag: '🎉',
        bp: '-2425px 0px',
    },
    u1F393: {
        en: 'mortar_board',
        zh: '毕业',
        tag: '🎓',
        bp: '-2450px 0px',
    },
    u1F434: {
        en: 'horse',
        zh: '马',
        tag: '🐴',
        bp: '-2475px 0px',
    },
    u1F436: {
        en: 'dog',
        zh: '狗',
        tag: '🐶',
        bp: '-2500px 0px',
    },
    u1F437: {
        en: 'pig',
        zh: '猪',
        tag: '🐷',
        bp: '-2525px 0px',
    },
    u1F451: {
        en: 'crown',
        zh: '王冠',
        tag: '👑',
        bp: '-2550px 0px',
    },
    u1F484: {
        en: 'lipstick',
        zh: '口红',
        tag: '💄',
        bp: '-2575px 0px',
    },
    u1F494: {
        en: 'broken_heart',
        zh: '伤心',
        tag: '💔',
        bp: '-2600px 0px',
    },
    u1F525: {
        en: 'fire',
        zh: '火了',
        tag: '🔥',
        bp: '-2625px 0px',
    },
    u1F556: {
        en: 'time',
        zh: '时间',
        tag: '🕖',
        bp: '-2650px 0px',
    },
    u1F648: {
        en: 'see_no_evil',
        zh: '不看',
        tag: '🙈',
        bp: '-2675px 0px',
    },
    u1F649: {
        en: 'hear_no_evil',
        zh: '不听',
        tag: '🙉',
        bp: '-2700px 0px',
    },
    u1F680: {
        en: 'rocket',
        zh: '火箭',
        tag: '🚀',
        bp: '-2725px 0px',
    },
    u2B50: {
        en: 'star',
        zh: '星星',
        tag: '⭐',
        bp: '-2750px 0px',
    },
    u23F0: {
        en: 'alarm_clock',
        zh: '钟表',
        tag: '⏰',
        bp: '-2775px 0px',
    },
    u23F3: {
        en: 'hourglass_flowing_sand',
        zh: '沙漏',
        tag: '⏳',
        bp: '-2800px 0px',
    },
    u26A1: {
        en: 'zap',
        zh: '闪电',
        tag: '⚡',
        bp: '-2825px 0px',
    },
    u26BD: {
        en: 'soccer',
        zh: '足球',
        tag: '⚽',
        bp: '-2850px 0px',
    },
    u26C4: {
        en: 'snowman',
        zh: '雪人',
        tag: '⛄',
        bp: '-2875px 0px',
    },
    u26C5: {
        en: 'partly_sunny',
        zh: '多云',
        tag: '⛅',
        bp: '-2900px 0px',
    },
    u261D: {
        en: 'point_up',
        zh: '第一',
        tag: '☝',
        bp: '-2925px 0px',
    },
    u263A: {
        en: 'relaxed',
        zh: '轻松',
        tag: '☺',
        bp: '-2950px 0px',
    },
    u1F44A: {
        en: 'punch',
        zh: '拳',
        tag: '👊',
        bp: '-2975px 0px',
    },
    u270B: {
        en: 'hand',
        zh: '手',
        tag: '✋',
        bp: '-3000px 0px',
    },
    u270C: {
        en: 'v',
        zh: 'v',
        tag: '✌',
        bp: '-3025px 0px',
    },
    u270F: {
        en: 'pencil2',
        zh: '笔',
        tag: '✏',
        bp: '-3050px 0px',
    },
    u2600: {
        en: 'sunny',
        zh: '晴朗',
        tag: '☀',
        bp: '-3075px 0px',
    },
    u2601: {
        en: 'cloud',
        zh: '云',
        tag: '☁',
        bp: '-3100px 0px',
    },
    u2614: {
        en: 'umbrella',
        zh: '伞',
        tag: '☔',
        bp: '-3125px 0px',
    },
    u2615: {
        en: 'coffee',
        zh: '咖啡',
        tag: '☕',
        bp: '-3150px 0px',
    },
    u2744: {
        en: 'snowflake',
        zh: '雪花',
        tag: '❄',
        bp: '-3175px 0px',
    },
}
